function persona(personId, rang, firstname,lastname,email)
{
//console.log("clani.jsFunctionpersona");		
this.personaId=personId;	
this.rang=rang;
this.firstname=firstname;
this.lastname=lastname;
this.email=email;
}
	//alert("clani.jsZunaj funkcije");	
clanZdravnik0=new persona("0","1","Tatjana","Pintar","pintart7@hotmail.com");
clanZdravnik1=new persona("1","1","Maja","&#352;o&#353;tari&#269;","maja.sos@siol.net");
clanZdravnik2=new persona("2","0","Nina","Kosma&#269;","kosmac.nina@siol.net");
clanZdravnik3=new persona("3","1","Bojan","Kontestabile","kontestabile@gmail.com");
clanZdravnik4=new persona("4","2","Nenad","Danojevi&#263;","ndanoj@gmail.com");
clanZdravnik5=new persona("5","1","&#352;pela","Mu&#353;i&#269;","spela.music@kclj.si");
clanZdravnik6=new persona("6","1","Gordan","Mijovski","gordan.mijovski@outlook.com");
clanZdravnik7=new persona("7","1","Dominika","Oroszy","dominika.oroszy@kclj.si");
clanZdravnik8=new persona("8","2","Karolina","Rode","karolina.rode@gmail.com");
clanZdravnik9=new persona("9","2","Ji&#345;&#237;","Hollan","jiri.hollan@gmail.com");
clanZdravnik10=new persona("10","2","Hana","Hollan","hana.hollan@gmail.com");
clanZdravnik11=new persona("11","2","Sabina","&#352;tivan","sabina.stivan@gmail.com");
clanZdravnik12=new persona("12","2","&#352;pela","&#352;tupnik","spelastupnik@hotmail.com");
clanZdravnik13=new persona("13","2","Mojca","Drnov&#353;ek Globokar","mojca.drnovsek@gmail.com");
clanZdravnik14=new persona("14","1","Marija","Bo&#382;inovska","dr.marijabozinovska@gmail.com");
clanZdravnik15=new persona("15","1","Gordana","Taleska","taleskagordana@gmail.com");
clanZdravnik16=new persona("16","1","Matej","Jenko","jenko.matej@gmail.com");
clanZdravnik17=new persona("17","2","Vesna","Jankovi&#269","vnovakjankovic@gmail.com");
clanZdravnik18=new persona("18","1","Sa&#353;a","&#381;ivkovi&#263;","sashaz@t-com.me");
clanZdravnik19=new persona("19","1","Dejan","Pirc","pirc.dejan@gmail.com");
clanZdravnik20=new persona("20","2","Jerneja","Ravnikar","jerneja.ravnikar@gmail.com");
clanZdravnik21=new persona("21","2","Tomislav","Mirkovi&#269","tomislav.mirkovic@mf.uni-lj.si");
clanZdravnik22=new persona("22","2","Alja","Skrt","alja.skrt@gmail.com");
clanZdravnik23=new persona("23","1","&#381;enja","Toma&#382;in&#269;i&#269;","zhabon@gmail.com");
clanZdravnik24=new persona("24","1","Ur&#353;a","&#381;erjav","ursazerjav@gmail.com");
clanZdravnik25=new persona("25","1","Valentina","Butkovi&#269","valentinabutkovic@yahoo.com");
clanZdravnik26=new persona("26","0","","","m");
clanZdravnik27=new persona("27","0","","","m");
var i;
var zdrClan = new Array();
zdrClan[0] = clanZdravnik0;
zdrClan[1] = clanZdravnik1;
zdrClan[2] = clanZdravnik2;
zdrClan[3] = clanZdravnik3;
zdrClan[4] = clanZdravnik4;
zdrClan[5] = clanZdravnik5;
zdrClan[6] = clanZdravnik6;
zdrClan[7] = clanZdravnik7;
zdrClan[8] = clanZdravnik8;
zdrClan[9] = clanZdravnik9;
zdrClan[10] = clanZdravnik10;
zdrClan[11] = clanZdravnik11;
zdrClan[12] = clanZdravnik12;
zdrClan[13] = clanZdravnik13;
zdrClan[14] = clanZdravnik14;
zdrClan[15] = clanZdravnik15;
zdrClan[16] = clanZdravnik16;
zdrClan[17] = clanZdravnik17;
zdrClan[18] = clanZdravnik18;
zdrClan[19] = clanZdravnik19;
zdrClan[20] = clanZdravnik20;
zdrClan[21] = clanZdravnik21;
zdrClan[22] = clanZdravnik22;
zdrClan[23] = clanZdravnik23;
zdrClan[24] = clanZdravnik24;
zdrClan[25] = clanZdravnik25;
zdrClan[26] = clanZdravnik26;
zdrClan[27] = clanZdravnik27;